(function () {
  const LensApp = window.LensApp || (window.LensApp = {});

  const STORAGE_KEYS = {
    profile: "lipPlannerProfile",
    includeDetailed: "lipPlannerIncludeDetailed",
    recommendation: "lipPlannerRecommendation",
    strategy: "lipPlannerStrategy",
    notes: "lipPlannerNotes",
    clientStatus: "lensClientStatus",
    clientView: "lensClientView",
    clientViewIntent: "lensClientViewIntent",
    clientRecords: "lensClientRecords",
    authUsers: "lipPlannerAuthUsers",
    authSession: "lipPlannerAuthSession",
    language: "lensLanguage",
    pendingClientRecords: "lensPendingClientRecords",
    linkedCaseRef: "lensLinkedCaseRef",
    linkedRecordId: "lensLinkedRecordId",
    federalTaxBrackets: "lensFederalTaxBrackets",
    temporaryAnalysisSession: "lensTemporaryAnalysisSession",
    analysisInternalNavigation: "lensAnalysisInternalNavigation"
  };

  const DEFAULT_SINGLE_FEDERAL_TAX_BRACKETS = [
    { rate: "10%", minIncome: "0", maxIncome: "11600" },
    { rate: "12%", minIncome: "11601", maxIncome: "47150" },
    { rate: "22%", minIncome: "47151", maxIncome: "100525" },
    { rate: "24%", minIncome: "100526", maxIncome: "191950" },
    { rate: "32%", minIncome: "191951", maxIncome: "243725" },
    { rate: "35%", minIncome: "243726", maxIncome: "609350" },
    { rate: "37%", minIncome: "609351", maxIncome: "" }
  ];

  const FEDERAL_TAX_BRACKET_FILINGS = [
    "Single",
    "Married Filing Jointly",
    "Married Filing Separately",
    "Head of Household",
    "Qualifying Surviving Spouse"
  ];
  const ADMIN_CREDENTIALS = {
    email: "admin@lens.com",
    password: "admin1001"
  };
  const DEFAULT_CLIENT_RECORDS = [
    {
      id: "cl-80421",
      viewType: "households",
      displayName: "Carter Household",
      lastName: "Carter",
      summary: "Household protection review",
      caseRef: "HH/80421",
      lastReview: "2026-03-10",
      insured: "2",
      source: "Referral",
      statusGroup: "in-review",
      statusLabels: ["Income", "Debt"],
      priority: "high",
      coverageAmount: 1850000,
      coverageGap: 1450000
    },
    {
      id: "cl-80437",
      viewType: "individuals",
      displayName: "Daniel Brooks",
      lastName: "Brooks",
      summary: "Key person coverage update",
      caseRef: "CL/80437",
      lastReview: "2026-03-08",
      insured: "Yes",
      source: "CPA",
      statusGroup: "coverage-placed",
      statusLabels: ["Business", "Estate"],
      priority: "medium",
      coverageAmount: 1200000,
      coverageGap: 780000
    },
    {
      id: "cl-80462",
      viewType: "individuals",
      displayName: "Sophia Nguyen",
      lastName: "Nguyen",
      summary: "Family education funding plan",
      caseRef: "CL/80462",
      lastReview: "2026-03-07",
      insured: "Yes",
      source: "Seminar",
      statusGroup: "prospects",
      statusLabels: ["Education", "Income"],
      priority: "high",
      coverageAmount: 2600000,
      coverageGap: 2100000
    },
    {
      id: "cl-80488",
      viewType: "individuals",
      displayName: "Michael Torres",
      lastName: "Torres",
      summary: "Mortgage and survivor income analysis",
      caseRef: "CL/80488",
      lastReview: "2026-03-05",
      insured: "Yes",
      source: "Website",
      statusGroup: "coverage-placed",
      statusLabels: ["Mortgage", "Needs"],
      priority: "medium",
      coverageAmount: 1350000,
      coverageGap: 920000
    },
    {
      id: "cl-80501",
      viewType: "households",
      displayName: "Mitchell Household",
      lastName: "Mitchell",
      summary: "Coverage review before renewal",
      caseRef: "HH/80501",
      lastReview: "2026-03-02",
      insured: "2",
      source: "Client Referral",
      statusGroup: "closed",
      statusLabels: ["Review", "Retention"],
      priority: "low",
      coverageAmount: 620000,
      coverageGap: 430000
    }
  ];

  const allSteps = [
    { id: "profile-1", label: "Link Profile", path: "profile.html" },
    { id: "analysis-setup", label: "Analysis Setup", path: "analysis-setup.html" },
    { id: "estimate", label: "Estimate Need", path: "analysis-estimate.html" },
    { id: "detail", label: "Detailed Analysis", path: "analysis-detail.html" },
    { id: "recommendations", label: "Coverage Options", path: "recommendations.html" },
    { id: "planner", label: "Policy Planner", path: "planner.html" },
    { id: "summary", label: "Summary", path: "summary.html" }
  ];
  const TRANSLATIONS = {
    en: {
      "pageTitle.home": "Life Evaluation & Needs Analysis",
      "pageTitle.lens": "LENS | Life Evaluation & Needs Analysis",
      "pageTitle.clients": "Clients | Advisor Planning Suite",
      "nav.records": "Records",
      "nav.clients": "Clients",
      "nav.financialProducts": "Products",
      "nav.resources": "Resources",
      "search.placeholder": "Search",
      "language.label": "Language",
      "language.english": "English",
      "language.spanish": "Spanish",
      "language.french": "French",
      "account.signIn": "Sign In",
      "account.welcome": "Welcome, {name}",
      "account.helpCenter": "Help Center",
      "account.settings": "Settings",
      "account.accountDetails": "Account Details",
      "account.signOut": "Sign Out",
      "account.adminView": "Admin View",
      "home.banner": "Built by Agents, for Agents",
      "home.eyebrow": "Home",
      "home.openLens": "Open LENS",
      "home.activeModuleText": "Life Evaluation & Needs Analysis is the active planning module currently available in this workspace.",
      "home.activeModuleLabel": "Active Module",
      "product.name": "Life Evaluation & Needs Analysis",
      "home.moduleDescription": "Guide clients through profile intake, need estimation, analysis review, recommendation framing, policy strategy discussion, and a final planning summary.",
      "home.metricWorkflow": "Workflow",
      "home.metricWorkflowValue": "Profile to Summary",
      "home.metricPurpose": "Purpose",
      "home.metricPurposeValue": "Needs-Based Planning",
      "home.metricFormat": "Format",
      "home.metricFormatValue": "Advisor-Facing",
      "home.notesLabel": "Workspace Notes",
      "home.notesText": "Use this home screen as a stable launch point for planning tools rather than dropping directly into a single calculator-like experience.",
      "home.searchLabel": "Search",
      "home.searchText": "The search bar is prepared for future cases, saved plans, internal references, and additional modules.",
      "lens.eyebrow": "Advisor Planning Workflow",
      "lens.subtitle": "A structured advisor tool for estimating life insurance needs and shaping durable protection strategies during client meetings.",
      "lens.copy": "Use a guided workflow to capture client data, evaluate death benefit needs, compare planning approaches, and frame thoughtful coverage recommendations without dropping into carrier-specific quoting.",
      "lens.startPlanning": "Start Planning",
      "lens.metricFocus": "Focus",
      "lens.metricFocusValue": "Needs-Based Planning",
      "lens.metricUseCase": "Use Case",
      "lens.metricUseCaseValue": "Advisor-Led Meetings",
      "clients.heading": "Client Directory",
      "clients.subtitle": "A dedicated space for client records and future case management tools.",
      "clients.helper": "This page is currently a placeholder for future client record workflows.",
      "clients.recordsLabel": "Client Records",
      "clients.mainHeading": "Client directory and saved case files",
      "clients.mainCopy": "This section is ready for future client search, saved plans, case notes, and status tracking. For now it acts as the first records destination in the main navigation.",
      "clients.metricStatus": "Status",
      "clients.metricStatusValue": "Placeholder",
      "clients.metricNextBuild": "Next Build",
      "clients.metricNextBuildValue": "Client List",
      "clients.metricPurposeValue": "Recordkeeping",
      "clients.plannedUseLabel": "Planned Use",
      "clients.plannedUseText": "Use this area later for recently viewed clients, search results, and cross-links into planning workflows.",
      "clients.currentStateLabel": "Current State",
      "clients.currentStateText": "Navigation is in place. Data-backed record management can be added when you are ready."
    },
    es: {
      "pageTitle.home": "Evaluacion de Vida y Analisis de Necesidades",
      "pageTitle.lens": "LENS | Evaluacion de Vida y Analisis de Necesidades",
      "pageTitle.clients": "Clientes | Suite de Planificacion para Asesores",
      "nav.records": "Records",
      "nav.clients": "Clientes",
      "nav.financialProducts": "Products",
      "nav.resources": "Resources",
      "search.placeholder": "Buscar",
      "language.label": "Idioma",
      "language.english": "Ingles",
      "language.spanish": "Espanol",
      "language.french": "Frances",
      "account.signIn": "Iniciar sesion",
      "account.welcome": "Bienvenido, {name}",
      "account.helpCenter": "Centro de ayuda",
      "account.settings": "Configuracion",
      "account.accountDetails": "Detalles de la cuenta",
      "account.signOut": "Cerrar sesion",
      "account.adminView": "Vista de administrador",
      "home.banner": "Creado por agentes, para agentes",
      "home.eyebrow": "Inicio",
      "home.openLens": "Abrir LENS",
      "home.activeModuleText": "Evaluacion de Vida y Analisis de Necesidades es el modulo activo disponible en este espacio de trabajo.",
      "home.activeModuleLabel": "Modulo activo",
      "product.name": "Evaluacion de Vida y Analisis de Necesidades",
      "home.moduleDescription": "Guie a los clientes a traves del perfil, la estimacion de necesidad, la revision del analisis, la recomendacion de cobertura, la estrategia de poliza y el resumen final.",
      "home.metricWorkflow": "Flujo",
      "home.metricWorkflowValue": "Perfil a resumen",
      "home.metricPurpose": "Objetivo",
      "home.metricPurposeValue": "Planificacion basada en necesidades",
      "home.metricFormat": "Formato",
      "home.metricFormatValue": "Orientado al asesor",
      "home.notesLabel": "Notas del espacio de trabajo",
      "home.notesText": "Use esta pantalla principal como punto de partida estable para herramientas de planificacion en lugar de entrar directamente en una sola calculadora.",
      "home.searchLabel": "Busqueda",
      "home.searchText": "La barra de busqueda esta preparada para futuros casos, planes guardados, referencias internas y modulos adicionales.",
      "lens.eyebrow": "Flujo de planificacion del asesor",
      "lens.subtitle": "Una herramienta estructurada para estimar necesidades de seguro de vida y definir estrategias de proteccion durante reuniones con clientes.",
      "lens.copy": "Use un flujo guiado para capturar datos del cliente, evaluar necesidades de beneficio por fallecimiento, comparar enfoques de planificacion y definir recomendaciones sin entrar en cotizaciones por aseguradora.",
      "lens.startPlanning": "Comenzar planificacion",
      "lens.metricFocus": "Enfoque",
      "lens.metricFocusValue": "Planificacion basada en necesidades",
      "lens.metricUseCase": "Caso de uso",
      "lens.metricUseCaseValue": "Reuniones dirigidas por asesores",
      "clients.heading": "Directorio de clientes",
      "clients.subtitle": "Un espacio dedicado a los registros de clientes y futuras herramientas de gestion de casos.",
      "clients.helper": "Esta pagina es actualmente un marcador para futuros flujos de trabajo de registros de clientes.",
      "clients.recordsLabel": "Registros de clientes",
      "clients.mainHeading": "Directorio de clientes y expedientes guardados",
      "clients.mainCopy": "Esta seccion esta lista para futuras busquedas de clientes, planes guardados, notas de casos y seguimiento de estado. Por ahora funciona como el primer destino de registros en la navegacion principal.",
      "clients.metricStatus": "Estado",
      "clients.metricStatusValue": "Marcador",
      "clients.metricNextBuild": "Siguiente desarrollo",
      "clients.metricNextBuildValue": "Lista de clientes",
      "clients.metricPurposeValue": "Mantenimiento de registros",
      "clients.plannedUseLabel": "Uso previsto",
      "clients.plannedUseText": "Use esta area mas adelante para clientes vistos recientemente, resultados de busqueda y enlaces a flujos de planificacion.",
      "clients.currentStateLabel": "Estado actual",
      "clients.currentStateText": "La navegacion ya esta lista. La gestion de registros con datos reales puede agregarse cuando este listo."
    },
    fr: {
      "pageTitle.home": "Evaluation de Vie et Analyse des Besoins",
      "pageTitle.lens": "LENS | Evaluation de Vie et Analyse des Besoins",
      "pageTitle.clients": "Clients | Suite de planification pour conseillers",
      "nav.records": "Records",
      "nav.clients": "Clients",
      "nav.financialProducts": "Products",
      "nav.resources": "Resources",
      "search.placeholder": "Recherche",
      "language.label": "Langue",
      "language.english": "Anglais",
      "language.spanish": "Espagnol",
      "language.french": "Francais",
      "account.signIn": "Se connecter",
      "account.welcome": "Bienvenue, {name}",
      "account.helpCenter": "Centre d'aide",
      "account.settings": "Parametres",
      "account.accountDetails": "Details du compte",
      "account.signOut": "Se deconnecter",
      "account.adminView": "Vue administrateur",
      "home.banner": "Cree par des agents, pour des agents",
      "home.eyebrow": "Accueil",
      "home.openLens": "Ouvrir LENS",
      "home.activeModuleText": "Evaluation de Vie et Analyse des Besoins est le module actif actuellement disponible dans cet espace de travail.",
      "home.activeModuleLabel": "Module actif",
      "product.name": "Evaluation de Vie et Analyse des Besoins",
      "home.moduleDescription": "Guidez les clients a travers le profil, l'estimation du besoin, l'analyse detaillee, la recommandation de couverture, la strategie de police et le resume final.",
      "home.metricWorkflow": "Flux",
      "home.metricWorkflowValue": "Du profil au resume",
      "home.metricPurpose": "Objectif",
      "home.metricPurposeValue": "Planification basee sur les besoins",
      "home.metricFormat": "Format",
      "home.metricFormatValue": "Destine aux conseillers",
      "home.notesLabel": "Notes de l'espace de travail",
      "home.notesText": "Utilisez cet ecran d'accueil comme point de depart stable pour les outils de planification plutot que d'entrer directement dans un seul calculateur.",
      "home.searchLabel": "Recherche",
      "home.searchText": "La barre de recherche est prete pour les futurs dossiers, plans enregistres, references internes et modules supplementaires.",
      "lens.eyebrow": "Flux de planification conseiller",
      "lens.subtitle": "Un outil structure pour estimer les besoins en assurance vie et definir des strategies de protection pendant les reunions clients.",
      "lens.copy": "Utilisez un flux guide pour saisir les donnees client, evaluer les besoins, comparer les approches de planification et formuler des recommandations sans passer par des devis assureur.",
      "lens.startPlanning": "Commencer",
      "lens.metricFocus": "Orientation",
      "lens.metricFocusValue": "Planification basee sur les besoins",
      "lens.metricUseCase": "Cas d'usage",
      "lens.metricUseCaseValue": "Reunions menees par le conseiller",
      "clients.heading": "Repertoire clients",
      "clients.subtitle": "Un espace dedie aux dossiers clients et aux futurs outils de gestion de cas.",
      "clients.helper": "Cette page est actuellement un espace reserve pour les futurs flux de gestion des dossiers clients.",
      "clients.recordsLabel": "Dossiers clients",
      "clients.mainHeading": "Repertoire clients et dossiers enregistres",
      "clients.mainCopy": "Cette section est prete pour la recherche client, les plans enregistres, les notes de dossier et le suivi du statut. Pour l'instant, elle sert de premier point d'entree des dossiers dans la navigation principale.",
      "clients.metricStatus": "Statut",
      "clients.metricStatusValue": "Espace reserve",
      "clients.metricNextBuild": "Prochaine etape",
      "clients.metricNextBuildValue": "Liste des clients",
      "clients.metricPurposeValue": "Tenue de dossiers",
      "clients.plannedUseLabel": "Usage prevu",
      "clients.plannedUseText": "Utilisez cet espace plus tard pour les clients recents, les resultats de recherche et les liens vers les flux de planification.",
      "clients.currentStateLabel": "Etat actuel",
      "clients.currentStateText": "La navigation est en place. La gestion des dossiers avec donnees reelles pourra etre ajoutee plus tard."
    }
  };

  LensApp.config = Object.assign(LensApp.config || {}, {
    STORAGE_KEYS,
    DEFAULT_SINGLE_FEDERAL_TAX_BRACKETS,
    FEDERAL_TAX_BRACKET_FILINGS,
    ADMIN_CREDENTIALS,
    DEFAULT_CLIENT_RECORDS,
    allSteps,
    TRANSLATIONS
  });
})();
